### ISSUE TITLE
Vowel plots with ggplot2 tutorial ready

### ISSUE THREAD

**Issue by JoeyStanley** [LingMethodsHub/LingMethodsHub.github.io#20]
Hi Joe and Matt. I've got my first contribution ready. It's largely the same as my rather popular [2018 tutorial](https://joeystanley.com/blog/making-vowel-plots-in-r-part-1) but just spruced up a little bit here and there. This is my first time doing this, so let me know if I've done something wrong. Here's the repo: https://github.com/JoeyStanley/vowel-plots-tutorial.

I guess to clarify, I've never forked a repo or done issues before, so I've probably done something wrong :)

**Comment by JoFrhwld** [comment]
Looks great! The one thing I’ll bring up for your attention now is that you *can*, if you want to, add more information to your author metadata. I figure you might minimally want to add your url:

https://quarto.org/docs/journals/authors.html#author-schema

You can also add (but don’t need to) add your affiliation info: 

https://quarto.org/docs/journals/authors.html#affiliations-schema

If you make any changes like that, just commit and push them, and I’ll merge it into the LMH branch.
