### ISSUE TITLE
Request for fork https://github.com/JoshuaWilsonBlack/animated_vowel_plots_tutorial

### ISSUE THREAD

**Issue by JoshuaWilsonBlack** [LingMethodsHub/LingMethodsHub.github.io#27]
Hi LingMethodsHub,

I have a tutorial currently hosted on my personal website covering fitting multiple models of changes in monophthong formant frequencies over time with the `purrr` package and then plotting the predictions of these models using `ggplot2` and `gganimate`.

It is currently hosted at <https://joshua.wilsonblack.nz/post/visualising-vowel-space-gamms/>, but it may be useful to others on the LingMethodsHub. Please let me know if you would like to add it to LingMethodsHub.

The url of the GitHub repo containing the tutorial is <https://github.com/JoshuaWilsonBlack/animated_vowel_plots_tutorial>

Many thanks,
Josh Wilson Black
("Wilson Black" is my surname).

**Comment by JoFrhwld** [comment]
Thanks for this (and sorry for the delay, we were on fall break over here). 

My one note that would be great to change up before lmh forks this would be to edit or delete the very last line (https://github.com/JoshuaWilsonBlack/animated_vowel_plots_tutorial/blob/8b7fd5c83bf4a6464201a30818af6f5f3d93bf8f/index.Rmd#L573) calling it a "blog post"?

**Comment by JoFrhwld** [comment]
Just an additional note: The tutorial compiled successfully as a standalone directory when I cloned it, meaning it ought to incorporate successfully into the LingMethodsHub site

**Comment by JoshuaWilsonBlack** [comment]
Hi, no problem about the delay. I thought I had changed that line, but it must have crept back in as I was moving files about! I've now deleted it from the repository.

**Comment by JoFrhwld** [comment]
It's live on the site now! https://lingmethodshub.github.io/content/R/animated_vowel_plots_tutorial/
