### ISSUE TITLE
Speaker Diarization for Linguistics: tutorial ready to fork

### ISSUE THREAD

**Issue by ibleaman** [LingMethodsHub/LingMethodsHub.github.io#33]
@JoFrhwld Our speaker diarization tutorial is ready to fork!
https://github.com/ibleaman/Speaker-Diarization-for-Linguistics

FYI the tutorial includes a link to an HTML page that directs the user to Google Colab if they want to easily diarize their own audio files. I'm planning to update this redirect later today, but it will have no impact on the notebook file itself.

(tagging @rsprouse)

**Comment by JoFrhwld** [comment]
Great! I’ve forked the repo and will start working on getting it added. My plan is to place the tutorial code under `contents/python`, which means its url will be `https://lingmethodshub.github.io/content/python/speaker-diarization-for-linguistics`. Some questions for you (@ibleaman, @rsprouse)

- Regardless of the url location, where would you like the tutorial to appear in the Contents navigation page?
    - [ ] Python/
    - [ ] Tools/
- What is your preferred medium of contact for further follow up questions about content & formatting?
    - [ ] This GitHub issue?
    - [ ] Work email?

When the tutorial is basically all set to go, I’ll send a pull request back to your original repository for you to review any formatting & metadata changes I’ve made.

**Comment by ibleaman** [comment]
Sounds good! Python and work email are my preferences.

**Comment by rsprouse** [comment]
Those preferences work for me too.
