### ISSUE TITLE
Re-nest LVC-r tutorials, or fix URL’s by hand

### ISSUE THREAD

**Issue by JoFrhwld** [LingMethodsHub/LingMethodsHub.github.io#34]
To get the citation info correct, the structure needs to be `directory/index.qmd`

Options:

a. Re-nest the tutorials that currently exist. This will break their current URLs.
b. Fix current urls by hand, replan new tutorials.

**Comment by matthuntgardner** [comment]
Sorry, I'm not sure what you are saying here. What I am currently doing in my tutorials is replacing the relative links with the full links by hand.
