### ISSUE TITLE
getVOT tutorial

### ISSUE THREAD

**Issue by rpuggaardrode** [LingMethodsHub/LingMethodsHub.github.io#48]
Hey! I tried writing up a recent presentation of mine on doing VOT prediction in R as a tutorial. 
Repo here: https://github.com/rpuggaardrode/getVOT-tutorial
The Rmd interacts with a few sound files which are also in the repo and won't render if they're not there, hope that's okay!

**Comment by JoFrhwld** [comment]
I’ve forked the repo, and will start working on it asap! I have some preliminary content questions:

1. I plan to convert the RMarkdown file to a Quarto file, which mostly involves reformatting the code-chunk options. Is that acceptable?
2. I see at the bottom there’s a paper citation. Is it ok if I reformat that to use Quarto citation syntax? (https://quarto.org/docs/authoring/footnotes-and-citations.html).

Once I’ve made the necessary edits and fleshed out the metadata, I’ll send a pull request from the LMH fork back to your repository. By default this will come back to the main branch, but if you’d like it sent to a different branch, be sure to create it and let me know.

**Comment by rpuggaardrode** [comment]
Cool! All good! The reason why the reference is just written out is because it's just there for data attribution, I don't actually refer to it anywhere in the tutorial

**Comment by JoFrhwld** [comment]
I've sent the pull request. Once you've merged it, I'll go ahead and publish the tutorial on the site.

**Comment by rpuggaardrode** [comment]
Done, thanks for the super quick processing!

**Comment by JoFrhwld** [comment]
you're live! https://lingmethodshub.github.io/content/R/getVOT-tutorial/

If at some point you want to make edits or update the tutorial, just make those commits in your repo and send a pull request back to the LMH fork https://github.com/LingMethodsHub/getVOT-tutorial
